//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deploy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deploy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be an empty Guid.
        /// </summary>
        internal static string Argument_EmptyGuid {
            get {
                return ResourceManager.GetString("Argument_EmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be null or empty.
        /// </summary>
        internal static string Argument_NullOrEmpty {
            get {
                return ResourceManager.GetString("Argument_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon file does not appear to be an ICO file.
        /// </summary>
        internal static string Package_InvalidIcon {
            get {
                return ResourceManager.GetString("Package_InvalidIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name cannot contain invalid path characters.
        /// </summary>
        internal static string Package_InvalidProductName {
            get {
                return ResourceManager.GetString("Package_InvalidProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package version must be 3-component consisting of major, minor and build.
        /// </summary>
        internal static string Package_InvalidVersion {
            get {
                return ResourceManager.GetString("Package_InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string Package_MissingFile {
            get {
                return ResourceManager.GetString("Package_MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name must be specified.
        /// </summary>
        internal static string Package_NoProductName {
            get {
                return ResourceManager.GetString("Package_NoProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product version must be specified.
        /// </summary>
        internal static string Package_NoProductVersion {
            get {
                return ResourceManager.GetString("Package_NoProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut name not specified.
        /// </summary>
        internal static string Package_NoShortcutName {
            get {
                return ResourceManager.GetString("Package_NoShortcutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade code must be specified.
        /// </summary>
        internal static string Package_NoUpgradeCode {
            get {
                return ResourceManager.GetString("Package_NoUpgradeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package contains too many files.
        /// </summary>
        internal static string Package_OverFileLimit {
            get {
                return ResourceManager.GetString("Package_OverFileLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform error during MSI package creation.
        /// </summary>
        internal static string Package_PlatformError {
            get {
                return ResourceManager.GetString("Package_PlatformError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product version must be greater than zero.
        /// </summary>
        internal static string Package_ProductVersionZero {
            get {
                return ResourceManager.GetString("Package_ProductVersionZero", resourceCulture);
            }
        }
    }
}
